language: go
sudo: false
os:
  - linux
  - osx
matrix:
  include:
  - go: tip
    env: GO111MODULE=on
  - go: 1.11.x
    env: GO111MODULE=on
  - go: 1.10.x
  - go: 1.9.x
  allow_failures:
    - go: tip
  fast_finish: true
script: 
- go test -v . -coverprofile=coverage.txt -covermode=atomic # ./... includes the vendor folder.
after_success:
  - bash <(curl -s https://codecov.io/bash)
