language: go
sudo: false
go:
  - 1.11.x
  - 1.12.x
  - tip
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - go: tip
    - os: windows
  fast_finish: true
env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org
script: 
- go test -v ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
